name: Realms
description: An Realms plugin created with love.
version: '${version}'
main: com.chunkslab.realms.RealmsPlugin
api-version: '1.18'
authors: [amownyy, ChunksLab]
website: https://chunkslab.com/
folia-supported: true
depend: [PlaceholderAPI]
softdepend:
  - WorldEdit
  - ItemsAdder
  - Oraxen